FROM nginx:alpine

# Копіюємо статичні файли
COPY index.html /usr/share/nginx/html/
COPY app.js /usr/share/nginx/html/

# Копіюємо конфігурацію nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]